const devs = [
    {
        id      : 1,
        name    : "Yahia ",
        age     : 25,
        skill   : "Ios Devs",
        location : "Mirpur",
        income  : 10000,
    },
    {
        id      : 2,
        name    : "Gias ",
        age     : 24,
        skill   : "Mern Devs",
        location : "Banani",
        income  : 20000,
    },
    {
        id      : 3,
        name    : "Fahim ",
        age     : 27,
        skill   : "Laravel Devs",
        location : "Uttara",
        income  : 100000,
    },
    {
        id      : 4,
        name    : "Rajib",
        age     : 32,
        skill   : "Php Devs",
        location : "Mirpur",
        income  : 25000,
    },
    {
        id      : 5,
        name    : "Jakaria",
        age     : 28,
        skill   : "Ios Devs",
        location : "Banani",
        income  : 23000,
    },
    {
        id      : 6,
        name    : "Kibria",
        age     : 23,
        skill   : "Mern Devs",
        location : "Uttara",
        income  : 29000,
    },
    {
        id      : 7,
        name    : "Delower",
        age     : 28,
        skill   : "Php Devs",
        location : "Mirpur",
        income  : 35000,
    },
    {
        id      : 8,
        name    : "Mojahid",
        age     : 34,
        skill   : "Laravel Devs",
        location : "Banani",
        income  : 27000,
    },
    {
        id      : 9,
        name    : "Mostakim",
        age     : 30,
        skill   : "Php Devs",
        location : "Uttara",
        income  : 42000,
    },
    {
        id      : 10,
        name    : "Asraful",
        age     : 33,
        skill   : "Ios Devs",
        location : "Mirpur",
        income  : 37000,
    },
    {
        id      : 11,
        name    : "Saiful",
        age     : 28,
        skill   : "Mern Devs",
        location : "Banani",
        income  : 54000,
    },
    {
        id      : 12,
        name    : "Hasan",
        age     : 28,
        skill   : "Php Devs",
        location : "Uttara",
        income  : 23000,
    },
    {
        id      : 13,
        name    : "Imran",
        age     : 28,
        skill   : "Ios Devs",
        location : "Mirpur",
        income  : 273000,
    },
    {
        id      : 14,
        name    : "Afzal",
        age     : 28,
        skill   : "Laravel Devs",
        location : "Banani",
        income  : 78000,
    },
    {
        id      : 15,
        name    : "Joinal",
        age     : 28,
        skill   : "Mern Devs",
        location : "Uttara",
        income  : 67000,
    },
    {
        id      : 16,
        name    : "Kalam",
        age     : 28,
        skill   : "Mern Devs",
        location : "Banani",
        income  : 87000,
    },
    {
        id      : 17,
        name    : "Azan",
        age     : 36,
        skill   : "Php Devs",
        location : "Uttara",
        income  : 28000,
    },
    {
        id      : 18,
        name    : "Saddam",
        age     : 37,
        skill   : "Mern Devs",
        location : "Mirpur",
        income  : 37000,
    },
    {
        id      : 19,
        name    : "Jakaria",
        age     : 45,
        skill   : "Php Devs",
        location : "Uttara",
        income  : 78000,
    },
    {
        id      : 20,
        name    : "Jakaria",
        age     : 47,
        skill   : "Laravel Devs",
        location : "Banani",
        income  : 64000,
    },
]
